// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.2
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_StartPlus_FullMethodName          = "/agent.AgentService/StartPlus"
	AgentService_StopPlus_FullMethodName           = "/agent.AgentService/StopPlus"
	AgentService_GetPlusStatus_FullMethodName      = "/agent.AgentService/GetPlusStatus"
	AgentService_ForwardMQTTMessage_FullMethodName = "/agent.AgentService/ForwardMQTTMessage"
	AgentService_MessageNotice_FullMethodName      = "/agent.AgentService/MessageNotice"
	AgentService_CreateTask_FullMethodName         = "/agent.AgentService/CreateTask"
	AgentService_StartTask_FullMethodName          = "/agent.AgentService/StartTask"
	AgentService_StopTask_FullMethodName           = "/agent.AgentService/StopTask"
	AgentService_GetTaskStatus_FullMethodName      = "/agent.AgentService/GetTaskStatus"
	AgentService_ListTasks_FullMethodName          = "/agent.AgentService/ListTasks"
	AgentService_LoadPlugin_FullMethodName         = "/agent.AgentService/LoadPlugin"
	AgentService_UnloadPlugin_FullMethodName       = "/agent.AgentService/UnloadPlugin"
	AgentService_ExecutePlugin_FullMethodName      = "/agent.AgentService/ExecutePlugin"
	AgentService_ListPlugins_FullMethodName        = "/agent.AgentService/ListPlugins"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the RPC interface between Base and Plus
type AgentServiceClient interface {
	// StartPlus starts the Plus process
	StartPlus(ctx context.Context, in *StartPlusRequest, opts ...grpc.CallOption) (*StartPlusResponse, error)
	// StopPlus stops the Plus process
	StopPlus(ctx context.Context, in *StopPlusRequest, opts ...grpc.CallOption) (*StopPlusResponse, error)
	// GetPlusStatus gets the status of the Plus process
	GetPlusStatus(ctx context.Context, in *GetPlusStatusRequest, opts ...grpc.CallOption) (*GetPlusStatusResponse, error)
	// ForwardMQTTMessage forwards MQTT messages from Base to Plus
	ForwardMQTTMessage(ctx context.Context, in *ForwardMQTTMessageRequest, opts ...grpc.CallOption) (*ForwardMQTTMessageResponse, error)
	// MessageNotice sync messages from Base to Plus
	MessageNotice(ctx context.Context, in *MessageNoticeRequest, opts ...grpc.CallOption) (*MessageNoticeResponse, error)
	// Task Management APIs
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
	GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Plugin Management APIs
	LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*LoadPluginResponse, error)
	UnloadPlugin(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*UnloadPluginResponse, error)
	ExecutePlugin(ctx context.Context, in *ExecutePluginRequest, opts ...grpc.CallOption) (*ExecutePluginResponse, error)
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StartPlus(ctx context.Context, in *StartPlusRequest, opts ...grpc.CallOption) (*StartPlusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPlusResponse)
	err := c.cc.Invoke(ctx, AgentService_StartPlus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopPlus(ctx context.Context, in *StopPlusRequest, opts ...grpc.CallOption) (*StopPlusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPlusResponse)
	err := c.cc.Invoke(ctx, AgentService_StopPlus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetPlusStatus(ctx context.Context, in *GetPlusStatusRequest, opts ...grpc.CallOption) (*GetPlusStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlusStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetPlusStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ForwardMQTTMessage(ctx context.Context, in *ForwardMQTTMessageRequest, opts ...grpc.CallOption) (*ForwardMQTTMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardMQTTMessageResponse)
	err := c.cc.Invoke(ctx, AgentService_ForwardMQTTMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) MessageNotice(ctx context.Context, in *MessageNoticeRequest, opts ...grpc.CallOption) (*MessageNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageNoticeResponse)
	err := c.cc.Invoke(ctx, AgentService_MessageNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_StartTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, AgentService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*LoadPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadPluginResponse)
	err := c.cc.Invoke(ctx, AgentService_LoadPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UnloadPlugin(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*UnloadPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadPluginResponse)
	err := c.cc.Invoke(ctx, AgentService_UnloadPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecutePlugin(ctx context.Context, in *ExecutePluginRequest, opts ...grpc.CallOption) (*ExecutePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePluginResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecutePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the RPC interface between Base and Plus
type AgentServiceServer interface {
	// StartPlus starts the Plus process
	StartPlus(context.Context, *StartPlusRequest) (*StartPlusResponse, error)
	// StopPlus stops the Plus process
	StopPlus(context.Context, *StopPlusRequest) (*StopPlusResponse, error)
	// GetPlusStatus gets the status of the Plus process
	GetPlusStatus(context.Context, *GetPlusStatusRequest) (*GetPlusStatusResponse, error)
	// ForwardMQTTMessage forwards MQTT messages from Base to Plus
	ForwardMQTTMessage(context.Context, *ForwardMQTTMessageRequest) (*ForwardMQTTMessageResponse, error)
	// MessageNotice sync messages from Base to Plus
	MessageNotice(context.Context, *MessageNoticeRequest) (*MessageNoticeResponse, error)
	// Task Management APIs
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Plugin Management APIs
	LoadPlugin(context.Context, *LoadPluginRequest) (*LoadPluginResponse, error)
	UnloadPlugin(context.Context, *UnloadPluginRequest) (*UnloadPluginResponse, error)
	ExecutePlugin(context.Context, *ExecutePluginRequest) (*ExecutePluginResponse, error)
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) StartPlus(context.Context, *StartPlusRequest) (*StartPlusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPlus not implemented")
}
func (UnimplementedAgentServiceServer) StopPlus(context.Context, *StopPlusRequest) (*StopPlusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPlus not implemented")
}
func (UnimplementedAgentServiceServer) GetPlusStatus(context.Context, *GetPlusStatusRequest) (*GetPlusStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlusStatus not implemented")
}
func (UnimplementedAgentServiceServer) ForwardMQTTMessage(context.Context, *ForwardMQTTMessageRequest) (*ForwardMQTTMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardMQTTMessage not implemented")
}
func (UnimplementedAgentServiceServer) MessageNotice(context.Context, *MessageNoticeRequest) (*MessageNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MessageNotice not implemented")
}
func (UnimplementedAgentServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedAgentServiceServer) StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTask not implemented")
}
func (UnimplementedAgentServiceServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedAgentServiceServer) GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedAgentServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAgentServiceServer) LoadPlugin(context.Context, *LoadPluginRequest) (*LoadPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadPlugin not implemented")
}
func (UnimplementedAgentServiceServer) UnloadPlugin(context.Context, *UnloadPluginRequest) (*UnloadPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadPlugin not implemented")
}
func (UnimplementedAgentServiceServer) ExecutePlugin(context.Context, *ExecutePluginRequest) (*ExecutePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlugin not implemented")
}
func (UnimplementedAgentServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StartPlus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartPlus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartPlus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartPlus(ctx, req.(*StartPlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopPlus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopPlus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopPlus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopPlus(ctx, req.(*StopPlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetPlusStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlusStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetPlusStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetPlusStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetPlusStatus(ctx, req.(*GetPlusStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ForwardMQTTMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardMQTTMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ForwardMQTTMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ForwardMQTTMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ForwardMQTTMessage(ctx, req.(*ForwardMQTTMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_MessageNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).MessageNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_MessageNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).MessageNotice(ctx, req.(*MessageNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_LoadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).LoadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_LoadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).LoadPlugin(ctx, req.(*LoadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UnloadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UnloadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UnloadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UnloadPlugin(ctx, req.(*UnloadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecutePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecutePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecutePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecutePlugin(ctx, req.(*ExecutePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPlus",
			Handler:    _AgentService_StartPlus_Handler,
		},
		{
			MethodName: "StopPlus",
			Handler:    _AgentService_StopPlus_Handler,
		},
		{
			MethodName: "GetPlusStatus",
			Handler:    _AgentService_GetPlusStatus_Handler,
		},
		{
			MethodName: "ForwardMQTTMessage",
			Handler:    _AgentService_ForwardMQTTMessage_Handler,
		},
		{
			MethodName: "MessageNotice",
			Handler:    _AgentService_MessageNotice_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _AgentService_CreateTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _AgentService_StartTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _AgentService_StopTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _AgentService_GetTaskStatus_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AgentService_ListTasks_Handler,
		},
		{
			MethodName: "LoadPlugin",
			Handler:    _AgentService_LoadPlugin_Handler,
		},
		{
			MethodName: "UnloadPlugin",
			Handler:    _AgentService_UnloadPlugin_Handler,
		},
		{
			MethodName: "ExecutePlugin",
			Handler:    _AgentService_ExecutePlugin_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _AgentService_ListPlugins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
